package com.beijing.cms.sys.dao.user;

import com.beijing.cms.sys.domain.user.SysFunction;

import java.util.List;

public interface SysFunctionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbggenerated
     */
    int deleteById(Integer functionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbggenerated
     */
    int insert(SysFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbggenerated
     */
    int insertSelective(SysFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbggenerated
     */
    SysFunction selectById(Integer functionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbggenerated
     */
    int updateByIdSelective(SysFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function
     *
     * @mbggenerated
     */
    int updateById(SysFunction record);

    /**
     * 查询所有菜单
     *
     * @return
     * @throws Exception
     */
    List<SysFunction> selectAllFunctionList() throws Exception;

    /**
     * 查询用户有权限的菜单
     * @param userId
     * @return
     * @throws Exception
     */
    List<SysFunction> selectFuncListByAuth(Integer userId) throws Exception;

    /**
     * 根据功能路径查询菜单数量
     *
     * @param functionUrl
     * @return
     * @throws Exception
     */
    SysFunction selectByFunctionUrl(String functionUrl) throws Exception;
}