package com.beijing.cms.sys.dao.user;

import com.beijing.cms.sys.domain.user.SysPermission;
import com.beijing.cms.sys.domain.user.SysUser;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * @program: cf-home
 * @description: ${description}
 * @author: mazeguo
 * @create: 2019-03-24 14:14
 **/
public interface SysPermissionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated
     */
    int deleteById(Integer permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated
     */
    int insert(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated
     */
    SysPermission selectById(Integer permissionId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated
     */
    int updateById(SysPermission record);

    /**
     * 删除用户权限
     *
     * @param sysUser
     * @throws Exception
     */
    void deleteByUserId(SysUser sysUser) throws Exception;

    /**
     * 根据用户Id查询权限数据
     *
     * @param userId
     * @return
     * @throws Exception
     */
    List<SysPermission> selectByUserId(Integer userId) throws Exception;

    /**
     * 根据角色Id查询 权限数据
     *
     * @param roleId
     * @return
     * @throws Exception
     */
    List<SysPermission> selectByRoleId(Integer roleId) throws Exception;

    /**
     * 根据用户
     * @param userId
     * @param roleCode
     * @return
     * @throws Exception
     */
    List<SysPermission> selectByUserIdAndRoleCode(@Param("userId")Integer userId, @Param("roleCode")String roleCode)throws Exception;
}
