package com.beijing.cms.sys.dao.user;

import com.beijing.cms.sys.domain.user.SysUserDepart;

/**
 * @program: cf-home
 * @description: ${description}
 * @author: mazeguo
 * @create: 2019-03-24 14:13
 **/
public interface SysUserDepartDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_depart
     *
     * @mbggenerated
     */
    int deleteById(Integer userDeptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_depart
     *
     * @mbggenerated
     */
    int insert(SysUserDepart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_depart
     *
     * @mbggenerated
     */
    int insertSelective(SysUserDepart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_depart
     *
     * @mbggenerated
     */
    SysUserDepart selectById(Integer userDeptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_depart
     *
     * @mbggenerated
     */
    int updateByIdSelective(SysUserDepart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_depart
     *
     * @mbggenerated
     */
    int updateById(SysUserDepart record);

    /**
     * 根据用户Id删除用户与部门关系
     *
     * @param sysUserDepart
     * @throws Exception
     */
    void deleteByUserId(SysUserDepart sysUserDepart) throws Exception;
}
