package com.beijing.cms.sys.domain.user;

import java.util.Date;

public class SysDepart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart.depart_id
     *
     * @mbggenerated
     */
    private Integer departId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart.depart_name
     *
     * @mbggenerated
     */
    private String departName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart.parent_depart_id
     *
     * @mbggenerated
     */
    private String parentDepartId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart.depart_level
     *
     * @mbggenerated
     */
    private Integer departLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart.depart_order
     *
     * @mbggenerated
     */
    private Integer departOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart.fax
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart.modified
     *
     * @mbggenerated
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_depart.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart.depart_id
     *
     * @return the value of sys_depart.depart_id
     *
     * @mbggenerated
     */
    public Integer getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart.depart_id
     *
     * @param departId the value for sys_depart.depart_id
     *
     * @mbggenerated
     */
    public void setDepartId(Integer departId) {
        this.departId = departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart.depart_name
     *
     * @return the value of sys_depart.depart_name
     *
     * @mbggenerated
     */
    public String getDepartName() {
        return departName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart.depart_name
     *
     * @param departName the value for sys_depart.depart_name
     *
     * @mbggenerated
     */
    public void setDepartName(String departName) {
        this.departName = departName == null ? null : departName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart.parent_depart_id
     *
     * @return the value of sys_depart.parent_depart_id
     *
     * @mbggenerated
     */
    public String getParentDepartId() {
        return parentDepartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart.parent_depart_id
     *
     * @param parentDepartId the value for sys_depart.parent_depart_id
     *
     * @mbggenerated
     */
    public void setParentDepartId(String parentDepartId) {
        this.parentDepartId = parentDepartId == null ? null : parentDepartId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart.address
     *
     * @return the value of sys_depart.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart.address
     *
     * @param address the value for sys_depart.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart.depart_level
     *
     * @return the value of sys_depart.depart_level
     *
     * @mbggenerated
     */
    public Integer getDepartLevel() {
        return departLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart.depart_level
     *
     * @param departLevel the value for sys_depart.depart_level
     *
     * @mbggenerated
     */
    public void setDepartLevel(Integer departLevel) {
        this.departLevel = departLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart.depart_order
     *
     * @return the value of sys_depart.depart_order
     *
     * @mbggenerated
     */
    public Integer getDepartOrder() {
        return departOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart.depart_order
     *
     * @param departOrder the value for sys_depart.depart_order
     *
     * @mbggenerated
     */
    public void setDepartOrder(Integer departOrder) {
        this.departOrder = departOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart.mobile
     *
     * @return the value of sys_depart.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart.mobile
     *
     * @param mobile the value for sys_depart.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart.fax
     *
     * @return the value of sys_depart.fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart.fax
     *
     * @param fax the value for sys_depart.fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart.creator
     *
     * @return the value of sys_depart.creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart.creator
     *
     * @param creator the value for sys_depart.creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart.created
     *
     * @return the value of sys_depart.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart.created
     *
     * @param created the value for sys_depart.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart.modifier
     *
     * @return the value of sys_depart.modifier
     *
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart.modifier
     *
     * @param modifier the value for sys_depart.modifier
     *
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart.modified
     *
     * @return the value of sys_depart.modified
     *
     * @mbggenerated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart.modified
     *
     * @param modified the value for sys_depart.modified
     *
     * @mbggenerated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart.deleted
     *
     * @return the value of sys_depart.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart.deleted
     *
     * @param deleted the value for sys_depart.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_depart.description
     *
     * @return the value of sys_depart.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_depart.description
     *
     * @param description the value for sys_depart.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}