package com.beijing.cms.sys.domain.user;

import java.util.Date;

public class SysRoleFunction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_function.role_func_id
     *
     * @mbggenerated
     */
    private Integer roleFuncId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_function.operation
     *
     * @mbggenerated
     */
    private String operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_function.function_id
     *
     * @mbggenerated
     */
    private Integer functionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_function.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_function.data_rule
     *
     * @mbggenerated
     */
    private String dataRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_function.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_function.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_function.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_function.modified
     *
     * @mbggenerated
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_function.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_function.role_func_id
     *
     * @return the value of sys_role_function.role_func_id
     * @mbggenerated
     */
    public Integer getRoleFuncId() {
        return roleFuncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_function.role_func_id
     *
     * @param roleFuncId the value for sys_role_function.role_func_id
     * @mbggenerated
     */
    public void setRoleFuncId(Integer roleFuncId) {
        this.roleFuncId = roleFuncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_function.operation
     *
     * @return the value of sys_role_function.operation
     * @mbggenerated
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_function.operation
     *
     * @param operation the value for sys_role_function.operation
     * @mbggenerated
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    public Integer getFunctionId() {
        return functionId;
    }

    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_function.data_rule
     *
     * @return the value of sys_role_function.data_rule
     * @mbggenerated
     */
    public String getDataRule() {
        return dataRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_function.data_rule
     *
     * @param dataRule the value for sys_role_function.data_rule
     * @mbggenerated
     */
    public void setDataRule(String dataRule) {
        this.dataRule = dataRule == null ? null : dataRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_function.creator
     *
     * @return the value of sys_role_function.creator
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_function.creator
     *
     * @param creator the value for sys_role_function.creator
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_function.created
     *
     * @return the value of sys_role_function.created
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_function.created
     *
     * @param created the value for sys_role_function.created
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_function.modifier
     *
     * @return the value of sys_role_function.modifier
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_function.modifier
     *
     * @param modifier the value for sys_role_function.modifier
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_function.modified
     *
     * @return the value of sys_role_function.modified
     * @mbggenerated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_function.modified
     *
     * @param modified the value for sys_role_function.modified
     * @mbggenerated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_function.deleted
     *
     * @return the value of sys_role_function.deleted
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_function.deleted
     *
     * @param deleted the value for sys_role_function.deleted
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}